-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgnISSDSOoGeJVU9JV
RSIf6ht+wHD/xRDx6+gZOaTO4g+gCgYIKoZIzj0DAQehRANCAARLdiRQe9kOaFvz
NV5URytpMhEOPJZVJ1E9NvDx1PtzHZBegla53brKn9wx8IvIdXsAtwQtB+Rk077N
iuNRYt+J
-----END PRIVATE KEY-----